import { createFeatureTour } from "../../../dist/index.js";

export default createFeatureTour({
  includeEstablishingShot: false,
  introPauseMs: 0,
  outroPauseMs: 0,
  steps: [
    {
      action: "move",
      cameraFollow: true,
      label: "Follow the cursor into the first product region",
      moveDurationMs: 1050,
      pauseMs: 250,
      pauseTarget: "camera",
      selector: "[data-demo='card-1']",
      zoom: 1.7,
    },
    {
      action: "move",
      cameraFollow: true,
      label: "Track across to the secondary proof card",
      moveDurationMs: 1050,
      pauseMs: 250,
      pauseTarget: "camera",
      selector: "[data-demo='card-2']",
      zoom: 1.6,
    },
    {
      action: "move",
      cameraFollow: true,
      label: "Travel back toward the operator controls",
      moveDurationMs: 1000,
      pauseMs: 250,
      pauseTarget: "camera",
      selector: "[data-demo='email']",
      zoom: 1.75,
    },
    {
      action: "type",
      cameraFollow: true,
      label: "Type a real-looking email",
      moveDurationMs: 850,
      pauseMs: 250,
      selector: "[data-demo='email']",
      text: "demo@atlas.dev",
      zoom: 1.95,
    },
    {
      action: "click",
      cameraFollow: true,
      label: "Follow the cursor into the CTA commit",
      moveDurationMs: 900,
      pauseMs: 500,
      selector: "[data-demo='cta']",
      zoom: 1.7,
    },
  ],
});
