export { defineConfig } from "./config.js";
export { defineScenes } from "./scenes.js";
export {
  createFeatureTour,
  createFormFillCapture,
  createHeroWalkthrough,
} from "./templates.js";
export type {
  CameraMode,
  CameraController,
  CameraFocusOptions,
  CompositionCaptionAlign,
  CompositionLayout,
  CompositionPreset,
  CameraSample,
  CameraState,
  CursorClickOptions,
  CursorController,
  CursorMoveOptions,
  CursorSample,
  CursorTypeOptions,
  DemoProgram,
  DemoContext,
  FeatureTourAction,
  FeatureTourOptions,
  FeatureTourStep,
  FfmpegPlan,
  FormFillCaptureOptions,
  FormFillField,
  HeroWalkthroughOptions,
  LoadedMotionConfig,
  MotionScene,
  MotionConfig,
  OutputFormat,
  OutputPreset,
  Point,
  SceneProgram,
  Size,
} from "./types.js";
