export { defineConfig } from "./config.js";
export { defineScenes } from "./scenes.js";
export type {
  CameraController,
  CameraFocusOptions,
  CompositionLayout,
  CompositionPreset,
  CameraSample,
  CameraState,
  CursorClickOptions,
  CursorController,
  CursorMoveOptions,
  CursorSample,
  CursorTypeOptions,
  DemoProgram,
  DemoContext,
  FfmpegPlan,
  LoadedMotionConfig,
  MotionScene,
  MotionConfig,
  OutputFormat,
  OutputPreset,
  Point,
  SceneProgram,
  Size,
} from "./types.js";
