import type { LoadedMotionConfig, Point } from "./types.js";
import type { ManualRecording, RecordedAction } from "./manual-recorder.js";

function quote(value: string): string {
  return JSON.stringify(value);
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.min(Math.max(value, minimum), maximum);
}

function estimateMoveDuration(previous: Point, next: Point): number {
  const distance = Math.hypot(next.x - previous.x, next.y - previous.y);
  return Math.round(clamp(260 + distance * 0.55, 260, 1200));
}

function estimatePause(durationMs: number): number {
  return Math.round(clamp(durationMs * 0.55, 120, 1600));
}

function actionPoint(action: RecordedAction, fallback: Point): Point {
  if ("x" in action && typeof action.x === "number" && typeof action.y === "number") {
    return {
      x: action.x,
      y: action.y,
    };
  }

  return fallback;
}

function emitCoordinateMove(
  lines: string[],
  currentPoint: Point,
  nextPoint: Point,
): Point {
  const durationMs = estimateMoveDuration(currentPoint, nextPoint);
  lines.push(
    `  await cursor.move({ x: ${Math.round(nextPoint.x)}, y: ${Math.round(nextPoint.y)} }, { durationMs: ${durationMs} });`,
  );
  return nextPoint;
}

function emitPreActionPause(
  lines: string[],
  previousTimeMs: number,
  actionTimeMs: number,
): void {
  const gapMs = Math.max(actionTimeMs - previousTimeMs, 0);

  if (gapMs >= 320) {
    lines.push(`  await cursor.wait(${estimatePause(gapMs)});`);
  }
}

function shouldMergeIntoTypeClick(
  action: RecordedAction,
  nextAction: RecordedAction | undefined,
): boolean {
  return (
    action.kind === "click" &&
    nextAction?.kind === "type" &&
    action.selector !== undefined &&
    action.selector === nextAction.selector
  );
}

export function buildGeneratedDemoSource(
  config: LoadedMotionConfig,
  recording: ManualRecording,
): string {
  const lines = [
    "// Generated by `motion-creator record`.",
    "// Tweak selectors, timing, and camera choreography as needed.",
    "",
    "export default async function demo({ cursor, page }) {",
  ];
  const initialPoint = {
    x: Math.round(config.viewport.width / 2),
    y: Math.round(config.viewport.height / 2),
  };
  let currentPoint = initialPoint;
  let previousActionTimeMs = 0;

  if (recording.actions.length === 0) {
    lines.push("  await cursor.wait(600);");
    lines.push("}");
    return lines.join("\n");
  }

  for (let index = 0; index < recording.actions.length; index += 1) {
    const action = recording.actions[index];
    const nextAction = recording.actions[index + 1];

    emitPreActionPause(lines, previousActionTimeMs, action.timeMs);

    if (action.kind === "click") {
      if (shouldMergeIntoTypeClick(action, nextAction)) {
        previousActionTimeMs = Math.max(previousActionTimeMs, action.timeMs);
        continue;
      }

      const nextPoint = actionPoint(action, currentPoint);

      if (action.selector) {
        const optionParts = [
          `durationMs: ${estimateMoveDuration(currentPoint, nextPoint)}`,
        ];

        if (action.button !== "left") {
          optionParts.push(`button: ${quote(action.button)}`);
        }

        lines.push(
          `  await cursor.clickSelector(${quote(action.selector)}, { ${optionParts.join(", ")} });`,
        );
        currentPoint = nextPoint;
      } else {
        currentPoint = emitCoordinateMove(lines, currentPoint, nextPoint);
        lines.push(`  await cursor.click({ button: ${quote(action.button)} });`);
      }
    }

    if (action.kind === "type") {
      const nextPoint = actionPoint(action, currentPoint);
      const optionParts = [`delayMs: ${action.delayMs}`];

      if (action.submit) {
        optionParts.push("submit: true");
      }

      if (action.selector) {
        optionParts.unshift(
          `durationMs: ${estimateMoveDuration(currentPoint, nextPoint)}`,
        );
        lines.push(
          `  await cursor.typeSelector(${quote(action.selector)}, ${quote(action.text)}, { ${optionParts.join(", ")} });`,
        );
        currentPoint = nextPoint;
      } else {
        currentPoint = emitCoordinateMove(lines, currentPoint, nextPoint);
        lines.push("  await cursor.click();");
        lines.push(
          `  await cursor.type(${quote(action.text)}, { ${optionParts.join(", ")} });`,
        );
      }
    }

    if (action.kind === "scroll") {
      const nextPoint = actionPoint(action, currentPoint);
      currentPoint = emitCoordinateMove(lines, currentPoint, nextPoint);
      lines.push('  await cursor.sample("wait");');
      lines.push(
        `  await page.mouse.wheel(${Math.round(action.deltaX)}, ${Math.round(action.deltaY)});`,
      );
      lines.push("  await cursor.wait(240);");
    }

    previousActionTimeMs = Math.max(previousActionTimeMs, action.timeMs);
  }

  lines.push("}");
  return lines.join("\n");
}
